version: "3.9"
services:
    webapp:
        image: registry.everytrade.io/everytrade-webapp:2022-10-05T1201
        volumes:
            - webapp-data:/root/everytrade/volatile
        ports:
            - "127.0.0.1:8080:8080"
        environment:
            EVERYTRADE_DB_HOST: db
            EVERYTRADE_DB_USER: everytrade
            EVERYTRADE_DB_PASSWORD: everytrade
            EVERYTRADE_INSTALL_HOST:
            EVERYTRADE_INSTALL_ON_PREMISE: 'true'
        depends_on:
            db:
                condition: service_healthy
        logging:
            driver: json-file
            options:
                max-size: "200M"
                max-file: "20"
                compress: "true"
        restart: unless-stopped
    db:
        image: registry.everytrade.io/everytrade-mysql:8.0.21
        volumes:
            - db-data:/var/lib/mysql
        expose:
            - "3306"
        environment:
            MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
            MYSQL_DATABASE: everytrade
            MYSQL_USER: everytrade
            MYSQL_PASSWORD : everytrade
        logging:
            driver: json-file
            options:
                max-size: "10M"
                max-file: "10"
                compress: "true"
        healthcheck:
            test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
            timeout: 10s
            retries: 10
        restart: unless-stopped
volumes:
    db-data:
    webapp-data:
