version: "3.7"
services:
    webapp:
        image: registry.everytrade.io/${WHALEBOOKS_IMAGE:-everytrade-webapp}:${WHALEBOOKS_VERSION:-latest}
        volumes:
            - webapp-data:/root/everytrade/volatile
        ports:
            - "127.0.0.1:8080:8080"
        environment:
            EVERYTRADE_DB_HOST: pgdb
            EVERYTRADE_DB_USER: whalebooks
            EVERYTRADE_DB_PASSWORD: ${POSTGRES_PASSWORD:?err}
            EVERYTRADE_INSTALL_HOST:
            EVERYTRADE_INSTALL_ON_PREMISE: 'true'
            SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE:-default}
        depends_on:
            - pgdb
        logging:
            driver: json-file
            options:
                max-size: "200M"
                max-file: "20"
                compress: "true"
        restart: unless-stopped
        deploy:
            resources:
                limits:
                    memory: ${WEBAPP_MEMORY_LIMIT:-14g}
    pgdb:
        image: registry.everytrade.io/whalebooks-pgdb:2022-10-31
        shm_size: 1gb
        volumes:
            - db-data:/var/lib/postgresql
        expose:
            - "5432"
        environment:
            POSTGRES_DB: ${POSTGRES_DB:-whalebooks}
            POSTGRES_USER: ${POSTGRES_USER:-whalebooks}
            POSTGRES_PASSWORD : ${POSTGRES_PASSWORD:?err}
        logging:
            driver: json-file
            options:
                max-size: "10M"
                max-file: "10"
                compress: "true"
        healthcheck:
            test: ["CMD-SHELL", "pg_isready"]
            timeout: 10s
            retries: 10
        restart: unless-stopped
volumes:
    db-data:
    webapp-data:
