version: "3.7"
services:
    webapp:
        image: registry.everytrade.io/everytrade-webapp:2022-10-27T1919
        volumes:
            - webapp-data:/root/everytrade/volatile
        ports:
            - "127.0.0.1:8080:8080"
        environment:
            EVERYTRADE_DB_HOST: db
            EVERYTRADE_DB_USER: everytrade
            EVERYTRADE_DB_PASSWORD: everytrade
            EVERYTRADE_INSTALL_HOST:
            EVERYTRADE_INSTALL_ON_PREMISE: 'true'
            SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE:-default}
        depends_on:
            - pgdb
        logging:
            driver: json-file
            options:
                max-size: "200M"
                max-file: "20"
                compress: "true"
        restart: unless-stopped
    pgdb:
        image: registry.everytrade.io/whalebooks-pgdb:2022-10-31
        volumes:
            - db-data:/var/lib/postgresql
        expose:
            - "5432"
        environment:
            POSTGRES_DB: ${POSTGRES_DB:-whalebooks}
            POSTGRES_USER: ${POSTGRES_USER:-whalebooks}
            POSTGRES_PASSWORD : ${POSTGRES_PASSWORD:?err}
        logging:
            driver: json-file
            options:
                max-size: "10M"
                max-file: "10"
                compress: "true"
        healthcheck:
            test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
            timeout: 10s
            retries: 10
        restart: unless-stopped
volumes:
    db-data:
    webapp-data:
